stages:
  - build
  - test
  
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job:
  image: maven:latest
  stage: test
  script:
    - echo "This job runs Any API tests"
    - "mvn clean verify serenity:aggregate"
    - echo "Any API test completed"
    - sleep 10

  artifacts:
     when: always
     expire_in: 1 week
     paths:
      - target/site/serenity/index.html
      - target/site/serenity/serenity-summary.html
